name: deploy to aliyun oss

on:
  push:
    barches:
      - master
  schedule:
  - cron:  '*/15 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # 切代码到 runner
    - uses: actions/checkout@v1
      with:
        submodules: true
    # 使用 node:10
    - name: use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    # npm install
    - name: npm install
      run: npm install
    - name: build data
      run: node build-origin.js
    - name: build site
      run: npm run build
    # 设置阿里云OSS的 id/secret，存储到 github 的 secrets 中
    - name: setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-beijing.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    # - name: 删除冗余文件
    #   run: ossutil rm oss://shanyue-ncov/static -rf
    #   if: github.event_name == 'schedule'
    - name: cp files to aliyun
      run: ossutil cp -rf build oss://shanyue-ncov/
    - name: set no-cache in sw.js
      run: ossutil set-meta oss://shanyue-ncov/index.html cache-control:"no-cache" --update -rf
    - name: set long term cache
      run: ossutil set-meta oss://shanyue-ncov/static cache-control:"max-age=31536000" --update -rf